CREATE TABLE IF NOT EXISTS fiat_rates (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    currency VARCHAR(255) NOT NULL,
    rate NUMERIC(19, 2) NOT NULL,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crypto_rates (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    currency VARCHAR(255) NOT NULL,
    rate NUMERIC(19, 2) NOT NULL,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
