CREATE TABLE IF NOT EXISTS fiat_rates (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    currency VARCHAR(255) NOT NULL UNIQUE,
    rate NUMERIC(19, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS crypto_rates (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    currency VARCHAR(255) NOT NULL UNIQUE,
    rate NUMERIC(19, 2) NOT NULL
);
CREATE TABLE IF NOT EXISTS currency_rate (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    currency VARCHAR(255) NOT NULL,
    rate NUMERIC(19, 2) NOT NULL,
    type VARCHAR(255) NOT NULL,
    time_stamp TIMESTAMP NOT NULL
);